"""v2_initial_schema

Revision ID: 89b2274efac9
Revises: 
Create Date: 2026-08-29 10:22:45.008422
"""
from __future__ import annotations

from alembic import op

import app.models.base
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

revision = '89b2274efac9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baseline_store',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('feature_id', sa.String(length=64), nullable=False),
    sa.Column('window_size', sa.String(length=16), nullable=False),
    sa.Column('hour_of_week', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expected_median', sa.Float(), nullable=False),
    sa.Column('variability_mad', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=16), nullable=False),
    sa.Column('fit_period_start', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('fit_period_end', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_baseline_store')),
    sa.UniqueConstraint('merchant_id', 'feature_id', 'window_size', 'hour_of_week', 'version', name='uq_baseline_merchant_feature_window_hour_ver')
    )
    with op.batch_alter_table('baseline_store', schema=None) as batch_op:
        batch_op.create_index('ix_baseline_merchant_lookup', ['merchant_id', 'window_size', 'hour_of_week'], unique=False)

    op.create_table('eval_store',
    sa.Column('eval_id', sa.String(length=128), nullable=False),
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('split', sa.String(length=32), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('window_size', sa.String(length=16), nullable=False),
    sa.Column('window_end', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('detector_name', sa.String(length=64), nullable=False),
    sa.Column('predicted_score', sa.Float(), nullable=False),
    sa.Column('action_tier', sa.String(length=16), nullable=False),
    sa.Column('ground_truth_label', sa.String(length=32), nullable=False),
    sa.Column('scenario_id', sa.String(length=64), nullable=True),
    sa.Column('loss_incurred', sa.Float(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('eval_id', name=op.f('pk_eval_store'))
    )
    with op.batch_alter_table('eval_store', schema=None) as batch_op:
        batch_op.create_index('ix_eval_merchant_window', ['merchant_id', 'window_size', 'window_end'], unique=False)
        batch_op.create_index('ix_eval_run_split', ['run_id', 'split'], unique=False)
        batch_op.create_index(batch_op.f('ix_eval_store_run_id'), ['run_id'], unique=False)

    op.create_table('feature_store',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('window_size', sa.String(length=16), nullable=False),
    sa.Column('window_end', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_feature_store')),
    sa.UniqueConstraint('merchant_id', 'window_size', 'window_end', name='uq_feature_merchant_window_ts')
    )
    with op.batch_alter_table('feature_store', schema=None) as batch_op:
        batch_op.create_index('ix_feature_merchant_ts', ['merchant_id', 'window_end'], unique=False)

    op.create_table('incident_store',
    sa.Column('incident_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('action_tier', sa.String(length=16), nullable=False),
    sa.Column('first_flag_time', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_flag_time', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('window_sizes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('exposure_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('baseline_confidence', sa.String(length=16), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('incident_id', name=op.f('pk_incident_store'))
    )
    with op.batch_alter_table('incident_store', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_store_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index('ix_incidents_merchant_status', ['merchant_id', 'status'], unique=False)
        batch_op.create_index('ix_incidents_timeline', ['first_flag_time', 'last_flag_time'], unique=False)

    op.create_table('raw_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('timestamp', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('ingested_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_raw_events'))
    )
    with op.batch_alter_table('raw_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_events_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_raw_events_merchant_id'), ['merchant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_events_timestamp'), ['timestamp'], unique=False)

    op.create_table('relationship_store',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('entity_type_a', sa.String(length=32), nullable=False),
    sa.Column('entity_id_a', sa.String(length=128), nullable=False),
    sa.Column('entity_type_b', sa.String(length=32), nullable=False),
    sa.Column('entity_id_b', sa.String(length=128), nullable=False),
    sa.Column('co_occurrence_count', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('window_end', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationship_store'))
    )
    with op.batch_alter_table('relationship_store', schema=None) as batch_op:
        batch_op.create_index('ix_rel_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_rel_merchant_entity_a', ['merchant_id', 'entity_type_a', 'entity_id_a'], unique=False)
        batch_op.create_index('ix_rel_merchant_entity_b', ['merchant_id', 'entity_type_b', 'entity_id_b'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship_store', schema=None) as batch_op:
        batch_op.drop_index('ix_rel_merchant_entity_b')
        batch_op.drop_index('ix_rel_merchant_entity_a')
        batch_op.drop_index('ix_rel_expires_at')

    op.drop_table('relationship_store')
    with op.batch_alter_table('raw_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_raw_events_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_raw_events_idempotency_key'))
        batch_op.drop_index(batch_op.f('ix_raw_events_event_type'))

    op.drop_table('raw_events')
    with op.batch_alter_table('incident_store', schema=None) as batch_op:
        batch_op.drop_index('ix_incidents_timeline')
        batch_op.drop_index('ix_incidents_merchant_status')
        batch_op.drop_index(batch_op.f('ix_incident_store_merchant_id'))

    op.drop_table('incident_store')
    with op.batch_alter_table('feature_store', schema=None) as batch_op:
        batch_op.drop_index('ix_feature_merchant_ts')

    op.drop_table('feature_store')
    with op.batch_alter_table('eval_store', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eval_store_run_id'))
        batch_op.drop_index('ix_eval_run_split')
        batch_op.drop_index('ix_eval_merchant_window')

    op.drop_table('eval_store')
    with op.batch_alter_table('baseline_store', schema=None) as batch_op:
        batch_op.drop_index('ix_baseline_merchant_lookup')

    op.drop_table('baseline_store')
    # ### end Alembic commands ###
