"""initial schema

Revision ID: e100040c21c3
Revises: 
Create Date: 2026-08-21 10:42:08.767631
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

import app.models.base
from sqlalchemy.dialects import postgresql

revision = 'e100040c21c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_actions',
    sa.Column('action_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('merchant_id', sa.String(length=128), nullable=True),
    sa.Column('sku_id', sa.String(length=128), nullable=True),
    sa.Column('timestamp', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('action_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('action_id', name=op.f('pk_agent_actions'))
    )
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.create_index('ix_agent_actions_agent_ts', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_agent_actions_session_seq', ['session_id', 'sequence_number'], unique=False)

    op.create_table('agent_delegations',
    sa.Column('delegation_id', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('purpose', sa.String(length=64), nullable=False),
    sa.Column('max_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('allowed_categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('forbidden_categories', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('allowed_merchants', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('allowed_actions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('merchant_policy', sa.String(length=32), nullable=False),
    sa.Column('approval_required_above', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('issued_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('delegation_id', name=op.f('pk_agent_delegations'))
    )
    with op.batch_alter_table('agent_delegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_delegations_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_delegations_customer_id'), ['customer_id'], unique=False)

    op.create_table('agent_sessions',
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('network_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('started_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_agent_sessions'))
    )
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_sessions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_sessions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_sessions_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_sessions_network_fingerprint'), ['network_fingerprint'], unique=False)

    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('application_id', sa.String(length=128), nullable=True),
    sa.Column('trust_tier', sa.String(length=32), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('agent_id', name=op.f('pk_agents'))
    )
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.String(length=128), nullable=False),
    sa.Column('cluster_key', sa.String(length=64), nullable=False),
    sa.Column('campaign_risk', sa.Float(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('customer_count', sa.Integer(), nullable=False),
    sa.Column('agent_count', sa.Integer(), nullable=False),
    sa.Column('device_count', sa.Integer(), nullable=False),
    sa.Column('shared_entities', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('transaction_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('graph_version', sa.String(length=64), nullable=False),
    sa.Column('detected_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', name=op.f('pk_campaigns')),
    sa.UniqueConstraint('cluster_key', name=op.f('uq_campaigns_cluster_key'))
    )
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.create_index('ix_campaigns_detected_at', ['detected_at'], unique=False)

    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('segment', sa.String(length=32), nullable=False),
    sa.Column('home_country', sa.String(length=2), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('customer_id', name=op.f('pk_customers'))
    )
    op.create_table('entity_relationships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=128), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=128), nullable=False),
    sa.Column('relationship', sa.String(length=48), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('first_seen', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('last_seen', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('observation_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_relationships')),
    sa.UniqueConstraint('source_type', 'source_id', 'target_type', 'target_id', 'relationship', name='uq_entity_relationships_edge')
    )
    with op.batch_alter_table('entity_relationships', schema=None) as batch_op:
        batch_op.create_index('ix_entity_relationships_target', ['target_type', 'target_id'], unique=False)

    op.create_table('evaluation_runs',
    sa.Column('run_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('dataset_id', sa.String(length=128), nullable=True),
    sa.Column('dataset_path', sa.String(length=512), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('detectors', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('cost_model', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('dataset_summary', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('threshold_sweep', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('leakage_check', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('report_path', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', app.models.base.UtcDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('run_id', name=op.f('pk_evaluation_runs'))
    )
    op.create_table('ingested_events',
    sa.Column('event_id', sa.String(length=128), nullable=False),
    sa.Column('event_type', sa.String(length=48), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('schema_version', sa.String(length=16), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=True),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('timestamp', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('received_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_ingested_events')),
    sa.UniqueConstraint('idempotency_key', name='uq_ingested_events_idempotency_key')
    )
    with op.batch_alter_table('ingested_events', schema=None) as batch_op:
        batch_op.create_index('ix_ingested_events_type_ts', ['event_type', 'timestamp'], unique=False)

    op.create_table('merchants',
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('risk_policy_id', sa.String(length=64), nullable=False),
    sa.Column('is_known', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('merchant_id', name=op.f('pk_merchants'))
    )
    op.create_table('orders',
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('sku_id', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('order_id', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_merchant_id'), ['merchant_id'], unique=False)

    op.create_table('risk_cases',
    sa.Column('case_id', sa.String(length=128), nullable=False),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('decision_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('transaction_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('analyst_notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('resolution', sa.String(length=64), nullable=True),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('case_id', name=op.f('pk_risk_cases')),
    sa.UniqueConstraint('campaign_id', name='uq_risk_cases_campaign_id')
    )
    with op.batch_alter_table('risk_cases', schema=None) as batch_op:
        batch_op.create_index('ix_risk_cases_status', ['status'], unique=False)

    op.create_table('risk_decisions',
    sa.Column('decision_id', sa.String(length=128), nullable=False),
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=160), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=True),
    sa.Column('customer_id', sa.String(length=128), nullable=True),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('campaign_id', sa.String(length=128), nullable=True),
    sa.Column('case_id', sa.String(length=128), nullable=True),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('transaction_risk', sa.Float(), nullable=True),
    sa.Column('behavior_risk', sa.Float(), nullable=True),
    sa.Column('campaign_risk', sa.Float(), nullable=True),
    sa.Column('intent_deviation', sa.Float(), nullable=True),
    sa.Column('rule_violation_score', sa.Float(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('feature_version', sa.String(length=64), nullable=False),
    sa.Column('feature_snapshot_hash', sa.String(length=64), nullable=False),
    sa.Column('feature_snapshot', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('model_versions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('degraded_components', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('component_health', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('decided_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('decision_id', name=op.f('pk_risk_decisions')),
    sa.UniqueConstraint('idempotency_key', name='uq_risk_decisions_idempotency_key')
    )
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_decisions_campaign_id'), ['campaign_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_risk_decisions_case_id'), ['case_id'], unique=False)
        batch_op.create_index('ix_risk_decisions_decided_at', ['decided_at'], unique=False)
        batch_op.create_index('ix_risk_decisions_txn', ['transaction_id'], unique=False)

    op.create_table('semantic_errors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=128), nullable=True),
    sa.Column('transaction_id', sa.String(length=128), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=False),
    sa.Column('raw_excerpt', sa.Text(), nullable=True),
    sa.Column('created_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_semantic_errors'))
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.String(length=128), nullable=False),
    sa.Column('merchant_id', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=128), nullable=False),
    sa.Column('agent_id', sa.String(length=128), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('order_id', sa.String(length=128), nullable=True),
    sa.Column('delegation_id', sa.String(length=128), nullable=True),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('merchant_category', sa.String(length=64), nullable=False),
    sa.Column('sku_id', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('coupon_id', sa.String(length=128), nullable=True),
    sa.Column('coupon_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('network_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('instrument_fingerprint', sa.String(length=128), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('timestamp', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('ingested_at', app.models.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_agent_ts', ['agent_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_coupon_id'), ['coupon_id'], unique=False)
        batch_op.create_index('ix_transactions_customer_ts', ['customer_id', 'timestamp'], unique=False)
        batch_op.create_index('ix_transactions_device_ts', ['device_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_network_fingerprint'), ['network_fingerprint'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_sku_id'), ['sku_id'], unique=False)
        batch_op.create_index('ix_transactions_ts', ['timestamp'], unique=False)

    op.create_table('risk_evidence',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('decision_id', sa.String(length=128), nullable=False),
    sa.Column('signal', sa.String(length=64), nullable=False),
    sa.Column('observed', sa.Text(), nullable=False),
    sa.Column('observed_value', sa.Float(), nullable=True),
    sa.Column('expected_value', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('direction', sa.String(length=24), nullable=False),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['decision_id'], ['risk_decisions.decision_id'], name=op.f('fk_risk_evidence_decision_id_risk_decisions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_evidence'))
    )
    with op.batch_alter_table('risk_evidence', schema=None) as batch_op:
        batch_op.create_index('ix_risk_evidence_signal', ['signal'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_evidence_signal')

    op.drop_table('risk_evidence')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_ts')
        batch_op.drop_index(batch_op.f('ix_transactions_sku_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_session_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_network_fingerprint'))
        batch_op.drop_index('ix_transactions_device_ts')
        batch_op.drop_index('ix_transactions_customer_ts')
        batch_op.drop_index(batch_op.f('ix_transactions_coupon_id'))
        batch_op.drop_index('ix_transactions_agent_ts')

    op.drop_table('transactions')
    op.drop_table('semantic_errors')
    with op.batch_alter_table('risk_decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_decisions_txn')
        batch_op.drop_index('ix_risk_decisions_decided_at')
        batch_op.drop_index(batch_op.f('ix_risk_decisions_case_id'))
        batch_op.drop_index(batch_op.f('ix_risk_decisions_campaign_id'))

    op.drop_table('risk_decisions')
    with op.batch_alter_table('risk_cases', schema=None) as batch_op:
        batch_op.drop_index('ix_risk_cases_status')

    op.drop_table('risk_cases')
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_merchant_id'))
        batch_op.drop_index(batch_op.f('ix_orders_customer_id'))

    op.drop_table('orders')
    op.drop_table('merchants')
    with op.batch_alter_table('ingested_events', schema=None) as batch_op:
        batch_op.drop_index('ix_ingested_events_type_ts')

    op.drop_table('ingested_events')
    op.drop_table('evaluation_runs')
    with op.batch_alter_table('entity_relationships', schema=None) as batch_op:
        batch_op.drop_index('ix_entity_relationships_target')

    op.drop_table('entity_relationships')
    op.drop_table('customers')
    with op.batch_alter_table('campaigns', schema=None) as batch_op:
        batch_op.drop_index('ix_campaigns_detected_at')

    op.drop_table('campaigns')
    op.drop_table('agents')
    with op.batch_alter_table('agent_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_sessions_network_fingerprint'))
        batch_op.drop_index(batch_op.f('ix_agent_sessions_device_id'))
        batch_op.drop_index(batch_op.f('ix_agent_sessions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_agent_sessions_agent_id'))

    op.drop_table('agent_sessions')
    with op.batch_alter_table('agent_delegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_delegations_customer_id'))
        batch_op.drop_index(batch_op.f('ix_agent_delegations_agent_id'))

    op.drop_table('agent_delegations')
    with op.batch_alter_table('agent_actions', schema=None) as batch_op:
        batch_op.drop_index('ix_agent_actions_session_seq')
        batch_op.drop_index('ix_agent_actions_agent_ts')

    op.drop_table('agent_actions')
    # ### end Alembic commands ###
